# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RwEsnZJ5Vu_ozryBRY__OUkpbFKo3eS4
"""

list1=[2,4,6,8,10]
square=[i**2 for i in list1]
print('square of the numbers are:',square)
cube=[i**3 for i in list1]
print('cube of the numbers :',cube)

